### ISSUE TITLE
Where to place event-ticket-plus-shortcode.php file?

### ISSUE THREAD

**Issue by thomastthai** [bastiW/event-ticket-plus-shortcode#1]
Thank you for the work! Would you add short directions in the README as to how to install this for newer users?

Something like:

1. Download the zip file
2. Upload via the WordPress plugin interface
3. Activate the plugin

**Comment by bastiW** [comment]
Thanks for your request. 

I have added some install instructions. 

currently i don't plan to release a zip file as you might need to make code modifications and I don't follow all WP Standards

**Comment by webguys2hire** [comment]
I get a fatal error 

Fatal error: Cannot redeclare woocommerce_quantity_input() (previously declared in /wp-content/plugins/woocommerce/includes/wc-template-functions.php:1580) in /wp-content/plugins/event-ticket-plus-shortcode/event-ticket-plus-shortcode.php on line 473

**Comment by bastiW** [comment]
Hi

Sorry, I don't have time to work on this plugin anymore

You're open to create a pull request

webguys2hire <notifications@github.com> schrieb am Sa., 15. Sep. 2018,
23:02:
